services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - mailpit
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_TCP_PORT: '${DB_PORT}'
            # --------------------------------------------------------------------
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    phpmyadmin:
        image: 'phpmyadmin:latest'
        ports:
            - '${FORWARD_PHPMYADMIN_PORT:-8008}:80'
        environment:
            PMA_HOST: '${DB_HOST}'
            # --------------------------------------------------------------------
            PMA_PORT: '${DB_PORT}'
        networks:
            - sail
        depends_on:
            - '${DB_HOST}'
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    buggregator:
        image: ghcr.io/buggregator/server:latest
        ports:
            # - 127.0.0.1:8000:8000
            # - 127.0.0.1:1020:1025
            # - 127.0.0.1:9910:9912
            # - 127.0.0.1:9910:9913
            # -----------------------------------------
            # - '${FORWARD_BUGGREGATOR_01_PORT:-8000}:8000'
            # - '${FORWARD_BUGGREGATOR_02_PORT:-1026}:1026'
            # - '${FORWARD_BUGGREGATOR_03_PORT:-9912}:9912'
            # - '${FORWARD_BUGGREGATOR_04_PORT:-9913}:9913'
            # -----------------------------------------
            # Exigido a partir de versión de Docker Compose (v3.2)
            - target: 8000
              published: '${FORWARD_BUGGREGATOR_01_PORT:-8000}'
              protocol: tcp
              mode: host
            - target: 1026
              published: '${FORWARD_BUGGREGATOR_02_PORT:-1026}'
              protocol: tcp
              mode: host
            - target: 9912
              published: '${FORWARD_BUGGREGATOR_03_PORT:-9912}'
              protocol: tcp
              mode: host
            - target: 9913
              published: '${FORWARD_BUGGREGATOR_04_PORT:-9913}'
              protocol: tcp
              mode: host
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
